### PR TITLE
Fixed issue where nodes don't animate on update

### PR DESCRIPTION
**Pull request by mit1221**

### CODE REVIEW

**Comment by slakh96** [comment]
Confused as to what the animation issue is? Things seem to behave the same on develop and this branch lol :shrug:

**Comment by mit1221** [comment]
Lol, it's hard to spot. Once the tree is loaded, try clicking on a node. You'll see that the node names no longer animate in. Only the links do.

**Review by slakh96 — APPROVED** [review]
Ah, yes I understand and it is working perfectly :ok_hand:  I noticed that this will cause a merge conflict with https://github.com/VerWiki/VerWikiApp/pull/10, so I applied your fix to my branch manually. Do you think we should instead just merge that one to avoid nasty merge conflicts?

**Comment by mit1221** [comment]
Ya, that sounds good.

**Pull request closed without merging**
